import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :targeted_survey, TargetedSurveyWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# config/prod.exs
config :targeted_survey, :logger, [
  {:handler, :my_sentry_handler, Sentry.LoggerHandler, %{
    config: %{
      metadata: [:file, :line],
      rate_limiting: [max_events: 10, interval: _1_second = 1_000],
      # Logs all messages with level `:error` and above to Sentry.
      # Remove :capture_log_messages and :level if you only want to report crashes.
      capture_log_messages: true,
      level: :error
    }
  }}
]


# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req



# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
